//https://sites.google.com/site/wheeloffortunepuzzlecompendium/home/compendium/season-31-compendium
var puzzles = {
    "Phrase":["ANYTHING IS POSSIBLE",
              "BACK IN THE DAY",
              "ROLL THE DICE",
              "COOKED TO ORDER",
              "WORTH EVERY PENNY",
              "ALWAYS IN DEMAND",
              "FOR HOTEL GUESTS ONLY",
              "LET'S TAKE IT TO THE NEXT LEVEL",
              "A TASTE OF ITALY",
              "SIT BACK AND ENJOY THE FLIGHT",
              "A STROKE OF GENIUS",
              "BEHIND SCHEDULE",
              "IS THIS GOING TO BE ON THE TEST?",
              "RAISE YOUR HAND IF YOU KNOW THE ANSWER",
              "THE GREATEST OF ALL TIME",
              "FULLY GROWN",
              "WAIT UNTIL YOUR MOM HEARS ABOUT THIS",
              "WHEN WILL YOU BE CHECKING IN?",
              "LET'S GET TO WORK",
              "HOME SWEET HOME",
              "I COULD USE SOME HELP PACKING",
              "IS IT SPRING BREAK ALREADY?",
              "THERE WAS NEVER ANY DOUBT",
              "WAY TOO HOT TO HANDLE",
              "MAKE EVERY SECOND COUNT",
              "NICE OF YOU TO NOTICE",
              "I GET YOUR DRIFT",
              "IT FEELS AS WARM AS BATHWATER",
              "BRING THE PICNIC BASKET",
              "CARVED BY HAND",
              "SMOOTH SAILING",
              "THE PROOF IS IN THE PUDDING",
              "OUT OF POCKET",
              "I'M SITTING ON TOP OF THE WORLD",
              "THIS IS A MOMENTOUS OCCASION",
              "WE'RE ON A ROLL",
              "A SIGHT FOR SORE EYES",
              "SAY THE MAGIC WORD",
              "IT MUST BE SEEN TO BE BELIEVED",
              "RIPE FOR THE PICKING",
              "FRESH OUT OF THE OVEN",
              "MY JAW HIT THE FLOOR",
              "THIS IS HAWAII WE'RE TALKING ABOUT",
              "THINGS TO DO AND SEE",
              "THE ELEMENT OF SURPRISE",
              "DON'T FORGET TO TIP YOUR DEALER",
              "VAGUELY FAMILIAR",
              "A LITTLE SLICE OF HEAVEN",
              "A BREATH OF FRESH AIR",
              "MOVING UPWARD",
              "FORGOT YOUR PASSWORD?",
              "KEEP YOUR CAMERA READY",
              "WHEN THE DUST SETTLES",
              "BY THE POUND",
              "THE TABLES ARE TURNING",
              "BEYOND WORDS",
              "DON'T GET BUZZED OUT",
              "NICE JOB",
              "A WEALTH OF FUN THINGS TO DO",
              "GIVE-AND-TAKE",
              "A TASTE OF THE GOOD LIFE",
              "YOU WON'T HEAR ME COMPLAINING",
              "HOLD ON TO YOUR HATS",
              "I'M ON THE LOOKOUT",
              "HIT THE GROUND RUNNING",
              "QUITE A PAIR",
              "TRUTH BE TOLD",
              "FOOD FOR THOUGHT",
              "INTERNATIONAL FLAVOR",
              "I'M LOVING LIFE RIGHT NOW",
              "LAUGH-OUT-LOUD FUNNY",
              "REBIRTH AND RENEWAL",
              "JUST GOOGLE IT",
              "UNFINISHED BUSINESS",
              "ECONOMY SIZE",
              "LOCATION LOCATION LOCATION",
              "WARM AND BREEZY",
              "IN A NUTSHELL",
              "BY ACCIDENT",
              "I'M BACK IN THE GAME",
              "HOW THE WEST WAS WON",
              "BET YOUR BOTTOM DOLLAR",
              "HANGING IN THE BALANCE",
              "FIT FOR A QUEEN",
              "BOTTOMS UP",
              "A RISK WORTH TAKING",
              "THE CAVALRY TO THE RESCUE",
              "WHAT A HOOT",
              "TURN ON A DIME",
              "KISS AND TELL",
              "A FIRST TIME FOR EVERYTHING",
              "YOU'VE GOT TO BE KIDDING ME",
              "A NEW LEASE ON LIFE",
              "THE MOMENT YOU'VE BEEN WAITING FOR",
              "STRAIGHT TO THE TOP",
              "THIS STUFF NEVER HAPPENS TO ME",
              "GOBBLED UP",
              "AN EMBARRASSMENT OF RICHES",
              "I'M IN THE ZONE",
              "HAPPY AND HEALTHY",
              "I'VE GOT HIGH HOPES",
              "THIS IS THE BEST GAME EVER!",
              "YOU CAUGHT ME BY SURPRISE",
              "HERE COMES THE WELCOME WAGON",
              "HOMEWARD BOUND",
              "FEAST YOUR EYES ON THIS",
              "RIGHT UP YOUR ALLEY",
              "GAME SET AND MATCH",
              "SOMEWHAT OF A SURPRISE",
              "IT TAKES TWO TO TANGO",
              "THE PINNACLE OF LUXURY",
              "THE ULTIMATE IN TRANQUILITY",
              "CASUAL BY DAY ELEGANT BY NIGHT",
              "TRY TO BRING IT BACK IN ONE PIECE",
              "TELL ME WHERE I'M GOING PAT",
              "THE VIEW IS SIMPLY AMAZING",
              "SOUNDS A BIT IFFY",
              "BEHIND CLOSED DOORS",
              "EVERY DAY FEELS LIKE SATURDAY",
              "HOORAY FOR HAPPY HOUR",
              "SHE'S MY PARTNER IN CRIME",
              "PLUG IT IN",
              "WHAT TO WEAR?",
              "CAN YOU KEEP A SECRET?",
              "THE SKY'S THE LIMIT",
              "FROM COAST TO COAST",
              "WORKS WONDERS",
              "MILEAGE MAY VARY",
              "A WALK IN THE PARK",
              "YOU HAVE TO SEE IT TO BELIEVE IT",
              "THE BEST TIME OF YOUR LIFE",
              "SITTING ON A GOLD MINE",
              "STOP TEXTING ME I'M CRAMMING FOR FINALS",
              "I DREW A BLANK",
              "I PROMISE TO CALL YOU WHEN I LAND",
              "HAVING AN IMPACT",
              "TRENDING ON TWITTER",
              "I THANK MY LUCKY STARS",
              "I CAN'T WIPE THE SMILE OFF MY FACE",
              "THIS IS GOING TO MAKE A GREAT STORY",
              "LET'S GET THE BALL ROLLING",
              "PINCH ME I THINK I'M DREAMING",
              "DOWNRIGHT HILARIOUS",
              "LET THE CELEBRATION BEGIN",
              "SCOOT OVER",
              "KEEP YOUR NOSE TO THE GRINDSTONE",
              "DIVERSE BACKGROUNDS",
              "OFF TO A FLYING STAR",
              "EXTRA EXTRA READ ALL ABOUT IT",
              "HISTORY IN THE MAKING",
              "WEIGHING MY OPTIONS",
              "A SMASHING SUCCESS",
              "HIT THE SACK",
              "YOU HEARD IT HERE FIRST",
              "AMERICA'S GAME",
              "DON'T MAKE ME PULL THIS CAR OVER",
              "I DON'T CARE WHO STARTED IT",
              "WHERE WOULD WE BE WITHOUT YOU?",
              "BARELY ENOUGH",
              "KEEP YOUR ELBOWS OFF THE TABLE",
              "SOME DAY YOU'LL THANK ME",
              "PAY A VISIT",
              "BACK BY POPULAR DEMAND",
              "STAY AFLOAT",
              "REQUIRES IMMEDIATE ATTENTION",
              "THEY'RE PLAYING OUR SONG",
              "GOODNESS GRACIOUS",
              "WHERE DO YOU THINK YOU'RE GOING?",
              "THE RIGHT PRICE",
              "HOLD YOUR HORSES",
              "THREE TWO ONE BLAST-OFF",
              "STATE OF EUPHORIA",
              "WHAT A DEAL!",
              "DON'T QUIBBLE",
              "A GREAT VALUE",
              "GOING OVERBOARD",
              "SLOWLY BUT SURELY",
              "LOOK WHO'S IN THE LEAD",
              "FIND YOUR GROOVE",
              "RACE TO THE FINISH",
              "BRING A HEARTY APPETITE",
              "AMONG FRIENDS",
              "REALITY CHECK",
              "SAVOR EVERY SINGLE MOMENT",
              "PLENTY OF TIME FOR BEACHCOMBING",
              "CUT TO THE CHASE",
              "PLUG IT IN",
              "PLEASE TAKE ME WITH YOU",
              "POINT AND CLICK",
              "WHO HAS THE REMOTE?",
              "CLASS ISN'T OVER YET"],
    "RhymeTime":["READY FREDDY",
                 "LOOSEY-GOOSEY",
                 "SPIN TO WIN",
                 "THE BEST NEVER REST",
                 "SNACK PACK",
                 "SLIM AND TRIM",
                 "DOORS AND FLOORS",
                 "TAKE A BREAK",
                 "THE PLAY OF THE DAY",
                 "THAT'S THE WAY TO PLAY",
                 "NO MUSS NO FUSS",
                 "SUGAR AND SPICE AND EVERYTHING NICE",
                 "USE IT OR LOSE IT",
                 "NOW THIS IS THE REAL DEAL",
                 "IT'S A FINE LINE",
                 "HERE TOGETHER FRIENDS FOREVER",
                 "FUN UNDER THE SUN",
                 "ABSOLUTELY POSITIVELY",
                 "HIKING AND BIKING",
                 "DOUBLE BUBBLE",
                 "HEALTH AND WEALTH",
                 "HONEY BUNNY",
                 "TOASTERS & ROASTERS",
                 "EAGER BEAVER",
                 "WHAT'S YOUR CLAIM TO FAME?",
                 "GO WITH THE FLOW",
                 "SHARING IS CARING",
                 "HOLY MOLY!",
                 "REFUSE TO LOSE",
                 "CHICK FLICK",
                 "SUNDAY FUN DAY",
                 "GAL PAL",
                 "THE LATEST AND GREATEST",
                 "ROUGH AND TOUGH",
                 "TUCKED AWAY IN A SECLUDED BAY",
                 "FROM ZERO TO HERO",
                 "TUTTI-FRUTTI",
                 "MILLIONS AND BILLIOONS"],
    "WhatAreYouDoing":["COMING THROUGH WITH FLYING COLORS",
                       "EXPRESSING MYSELF",
                       "DINING BY MOONLIGHT",
                       "POSING FOR A PICTURE",
                       "GRADING EXAMS",
                       "MAKING A TRIPLE PLAY",
                       "LOOKING FOR ADVENTURE",
                       "SOLVING WORD PROBLEMS",
                       "PICKING THE PERFECT POSTCARD",
                       "MAKING LEMONADE",
                       "DRINKING SWEET TEA ON THE PORCH",
                       "SHOPPING FOR BARGAINS",
                       "LIGHTING THE TIKI TORCHES",
                       "MAKING RESERVATIONS",
                       "WRITING ON A COCKTAIL NAPKIN",
                       "CALLING THE SHOTS",
                       "REQUESTING A LATE CHECKOUT",
                       "GETTING DOWN TO THE NITTY-GRITTY",
                       "WATCHING THE SUNRISE FROM THE DECK",
                       "WRAPPING GIFTS",
                       "MAKING A PIT STOP",
                       "RINGING IN THE NEW YEAR",
                       "VISITING THE CONCIERGE DESK",
                       "PREDICTING THE FUTURE",
                       "MAKING RESOLUTIONS",
                       "EATING WITH CHOPSTICKS",
                       "GETTING IN ON THE GROUND FLOOR",
                       "TOSSING A SALAD",
                       "QUENCHING MY THIRST",
                       "COLLECTING COUPONS",
                       "SIGNING UP FOR THE NEWSLETTER",
                       "BEAMING WITH PRIDE",
                       "HITCHING A RIDE",
                       "GETTING DIRECTIONS TO THE BEACH",
                       "TAKING THE BULL BY THE HORNS",
                       "WORKING HARD TO FINISH THE JOB",
                       "READING A THERMOMETER",
                       "BASKING IN THE RADIANT SUNSHINE",
                       "JUST MAKING CONVERSATION",
                       "BRINGING DOWN THE HOUSE",
                       "WHISPERING SWEET NOTHINGS",
                       "SHOWING OFF MY VICTORY DANCE",
                       "EXPRESSING MY FEELINGS",
                       "ENJOYING A MORNING MIMOSA",
                       "WAFFLING",
                       "TYING UP A FEW LOOSE ENDS",
                       "GOING FOR BROKE",
                       "PLANTING FLOWERS",
                       "SITTING IN THE SAUNA",
                       "JUMPING AT THE CHANCE",
                       "WINDOW-SHOPPING",
                       "TESTING THE WATERS",
                       "LAUGHING HYSTERICALLY",
                       "BACKPACKING",
                       "EVOLVING",
                       "PLAYING BOARD GAMES",
                       "LEAVING FOOTPRINTS IN THE SAND",
                       "SITTING ON THE FRONT PORCH",
                       "BORROWING YOUR SWEATER",
                       "PLAYING THE RADIO AS LOUD AS WE WANT",
                       "BACKPEDALING",
                       "SLIPPING OFF MY FLIP-FLOPS",
                       "ORDERING APPETIZERS",
                       "PUTTING AIR IN THE TIRES",
                       "STOPPING FOR GAS",
                       "VISITING ALL FIFTY STATES",
                       "ASKING FOR DIRECTIONS",
                       "ORDERING BEVERAGES POOLSIDE",
                       "FLEXING MY MUSCLES",
                       "HITTING THE GYM",
                       "SEARCHING FOR BURIED TREASURE",
                       "MEETING MY DEADLINE",
                       "GETTING WARMED UP",
                       "DOWNLOADING MUSIC",
                       "SAVING UP FOR A RAINY DAY",
                       "PACKING WATERPROOF SUNSCREEN",
                       "BENDING THE RULES",
                       "BOOKING MY SHORE EXCURSION",
                       "SPEAKING MY MIND",
                       "SETTING SAIL FOR THE MEDITERRANEAN",
                       "FALLING ASLEEP IN A HAMMOCK",
                       "RACING AGAINST THE CLOCK",
                       "BLOWING KISSES",
                       "SWEETENING THE DEAL",
                       "CLEARING MY CALENDAR",
                       "GAZING INTO A CRYSTAL BALL",
                       "BROWSING ONLINE",
                       "LAUGHING UP A STORM",
                       "CLIMBING UP A COCONUT TREE",
                       "MAKING TRAVEL PLANS",
                       "SOAKING UP THE BEAUTY OF THE BIG ISLAND",
                       "PASSING THE BATON",
                       "READING A MAP",
                       "FIXING THINGS AROUND THE HOUSE",
                       "CATCHING MY SECOND WIND",
                       "PARKING THE CAR",
                       "WORKING OUT WITH DUMBBELLS"],
    "Title": ["ROCK OF AGES",
              "THE CHRONICLES OF NARNIA",
              "BAYWATCH",
              "TO KILL A MOCKINGBIRD",
              "JAWS",
              "CLOUDY WITH A CHANCE OF MEATBALLS",
              "A TALE OF TWO CITIES",
              "A STREETCAR NAMED DESIRE",
              "THE SECRET LIFE OF WALTER MITTY",
              "BREAKFAST AT TIFFANY'S",
              "HE'S JUST NOT THAT INTO YOU",
              "THE BRADY BUNCH",
              "MAGICAL MYSTERY TOUR",
              "BUFFY THE VAMPIRE SLAYER",
              "THE SOUND OF MUSIC",
              "VANITY FAIR"],
    "Thing": ["A REAL SHOWSTOPPER",
              "CORNER CURIO CABINET",
              "AN ENGINEERING MARVEL",
              "WALL SAFE",
              "FRIENDLY COMPETITION",
              "RANDOM ACT OF KINDNESS",
              "OVERHEAD PROJECTOR",
              "GLIMMERING TURQUOISE WATER",
              "COMPUTER SOFTWARE",
              "QUICK DECISION",
              "PAISLEY DESIGN",
              "STOCKY BUILD",
              "HOUSEHOLD BUDGET",
              "LOOSE-LEAF NOTEBOOK",
              "ELECTRIC PENCIL SHARPENER",
              "POWER PACK",
              "CURSIVE HANDWRITING",
              "DESK ORGANIZER",
              "FIXER-UPPER",
              "PAGER",
              "TOUGH COMPETITION",
              "OAK PLANK",
              "MURKY WATER",
              "CEREAL BOX",
              "BRIDAL REGISTRY",
              "ROLODEX",
              "FRENCH MANICURE",
              "CHURCH PEW",
              "CARRY-ON LUGGAGE",
              "DEPOSIT SLIP",
              "HARPSICHORD",
              "ARMORED CAR",
              "ANTIQUE WATCH",
              "IT'S OUT OF THE WAY",
              "LIFELIKE STATUE",
              "YOUR WORST NIGHTMARE",
              "WEB BROWSER",
              "WICKER HAMPER",
              "SEAT BELT BUCKLE",
              "QUIRKY PERSONALITY",
              "HOROSCOPE",
              "COMPUTER JARGON",
              "GOOD KARMA",
              "JOURNAL",
              "BEACHFRONT SWIMMING POOL",
              "OFFBEAT COMEDY",
              "CULT CLASSIC BOOK",
              "BEAUTIFUL SMILE",
              "BEDROCK",
              "HARD-HITTING INTERVIEW",
              "BULLFROG",
              "EXHIBITION",
              "PHOTOGRAPHIC MEMORY",
              "YOUR HOMEWORK",
              "EXERCISE ROUTINE",
              "BEVELED FRAME",
              "HEALTHY LIFESTYLE",
              "HYBRID VEHICLE",
              "UPLIFTING SPEECH",
              "WILD CARD",
              "A LASTING IMPRESSION",
              "FLUFFY WOOL",
              "WORLD-RENOWNED ART COLLECTION",
              "PINK FEATHER BOA",
              "COMPLIMENTARY LIMOUSINE RIDE",
              "POLAR BEAR CLUB",
              "GUTSY CHOICE",
              "DESSERT CART",
              "PREVAILING WIND",
              "MARVELOUS VACATION PACKAGE",
              "DIGITAL EDITION OF A MAGAZINE",
              "LOGICAL OUTCOME",
              "A SHINY NEW BIKE",
              "BACKUP PLAN",
              "ENGAGEMENT RING",
              "HEART-SHAPED PENDANT",
              "ITCHY PALM",
              "FEBRUARY FOURTEENTH",
              "WRITTEN TEST",
              "SILK HANDKERCHIEF",
              "CHOREOGRAPHY",
              "LOCKER KEY",
              "PERFECT OPPORTUNITY",
              "JUNCTION",
              "BODY OF WORK",
              "HOUSE KEY",
              "THOUGHTFULNESS",
              "STRESS-RELIEVING WHIRLPOOL",
              "EXPENSE REPORT",
              "COMPANY POLICY",
              "WORLD-CLASS HOSPITALITY",
              "GUILTY PLEASURE",
              "BOX OF BAKING SODA",
              "SUNKEN TREASURE",
              "OPEN VAULT",
              "HUMIDITY",
              "ONE OF OUR FAVORITE PLAYLISTS",
              "WOVEN HANDBAG",
              "HOT PROSPECT",
              "TANTALIZING BUFFET",
              "A NUGGET OF INFORMATION",
              "FRESH APPROACH",
              "RECOMMENDED DAILY SERVING",
              "CHOPPED FIREWOOD",
              "PAY TV",
              "THE PITTER-PATTER OF LITTLE FEET",
              "NEW BABY BUGGY",
              "GROUNDBREAKING WORK",
              "FATHERHOOD",
              "FINAL COUNTDOWN",
              "COMPLIMENTARY UPGRADE",
              "ONION SOUP",
              "BUSINESS SAVVY",
              "LUCKY PENNY",
              "A BRIEF EXPLANATION",
              "RECREATIONAL VEHICLE",
              "GOLD NUGGET",
              "LAVA HEADING TOWARD THE OCEAN",
              "PSYCHOLOGY",
              "BLOG POST",
              "ON-THE-JOB TRAINING",
              "THE LATEST TECHNOLOGY",
              "ON-THE-SPOT DECISION",
              "STEAM SHOWER",
              "A ROUND OF APPLAUSE",
              "COLD HARD CASH",
              "BREEZY DAY",
              "LIFETIME GUARANTEE",
              "HOBBYHORSE",
              "ATTITUDE ADJUSTMENT",
              "SPIRAL STAIRCASE",
              "MONUMENTAL ACHIEVEMENT",
              "VALIANT EFFORT",
              "BIKE PUMP",
              "THE NOBEL PEAE PRIZE",
              "RAPID GROWTH",
              "KANGAROO POUCH",
              "FUDGE CAKE",
              "BEDTIME STORY",
              "GRASS SKIRT",
              "VIVID IMAGINATION",
              "THE NORTH STAR",
              "HEAVENLY BODY",
              "GOOD SPORTSMANSHIP",
              "UNSOLICITED ADVICE",
              "PURCHASING POWER",
              "OFFICIAL LETTERHEAD",
              "CARDIGAN SWEATER",
              "UNANIMOUS VOTE",
              "MULTI-COLORED CONFETTI",
              "CALENDAR OF EVENTS",
              "HIRING PROCESS",
              "ROWBOAT",
              "DOG BOWL",
              "A FAMILY TRADITION",
              "ALL-OUT BLITZ",
              "DIGITAL DOWNLOAD",
              "LUGGAGE",
              "EXCELLENT TRACK RECORD"],
    "Place": ["THEATER BALCONY",
              "SIDEWALK CAFE",
              "FANCY BOUTIQUE",
              "SUMMER CAMP",
              "CASUAL DINING RESTAURANT",
              "POOLSIDE CABANA",
              "PACIFIC ISLAND PARADISE",
              "SCIENCE LAB",
              "DESERT OASIS",
              "SUPERHERO HEADQUARTERS",
              "DOG PARK",
              "FOOTBALL STADIUM",
              "THE CREEPY BATES MOTEL IN PSYCHO",
              "VISITOR CENTER",
              "DUCK POND",
              "ANCIENT GREECE",
              "ENGINE ROOM",
              "A SUITE WITH A VIEW OF THE OCEAN",
              "THE GREATEST NATION IN THE WORLD",
              "APPLE ORCHARD",
              "VEGETABLE GARDEN",
              "STATE CAPITAL",
              "A VIBRANT TROPICAL SETTING",
              "MAJOR HUB",
              "AN ABBEY",
              "FRONT ROW CENTER",
              "UPSCALE NEIGHBORHOOD",
              "BALCONY OVERLOOKING THE BEACH",
              "SCENIC OVERLOOK",
              "CIRCUS BIG TOP",
              "TRAVEL AGENCY",
              "TURNPIKE TOLLBOOTH",
              "ROOFTOP INFINITY POOL",
              "LIFEGUARD STATION",
              "BEAUTY PARLOR",
              "THE ISLAND OF ENCHANTMENT",
              "RAINBOW-COLORED CORAL REEF",
              "COBBLESTONE STREET",
              "MOUNTAIN LODGE",
              "WEST OF HAITI SOUTH OF CUBA",
              "MAIN STREET",
              "CANDY SHOP",
              "BREATHTAKING MARINE HABITAT",
              "PRIVATE HIDEAWAY",
              "A SPRAWLING ALL-INCLUSIVE RESORT",
              "BLACK SAND BEACH",
              "RECORDING STUDIO",
              "PREMIER DIVING DESTINATION",
              "ROMANTIC OPEN-AIR RESTAURANT",
              "CONCESSION STAND",
              "SEASIDE GARDEN PARADISE",
              "CONVENIENCE STORE",
              "TWO-CAR DETACHED GARAGE",
              "BUSY BOULEVARD",
              "BAIT & TACKLE SHOP"],
    "BeforeAndAfter":["STICKY SITUATION COMEDY",
                      "OUTER SPACE HEATER",
                      "MEMBERS-ONLY CLUB SANDWICH",
                      "MONOPOLY MONEY CAN'T BUY ME LOVE",
                      "BOWLING ALLEY CAT",
                      "JEDI MASTER BEDROOM",
                      "COMBINATION LOCK OF HAIR",
                      "FACULTY LOUNGE SINGER",
                      "CARTOON CHARACTER WITNESS",
                      "TERM PAPER OR PLASTIC",
                      "HOME SWEET HOME FRIES",
                      "MONTEREY JACK AND JILL",
                      "DAIRY FREE PARKING",
                      "ALL THE WORLD'S A STAGE FRIGHT",
                      "STOP IN THE NAME OF LOVE HANDLES",
                      "VICTORIA'S SECRET COMPARTMENT",
                      "IRON MAN OF THE YEAR",
                      "NEON LIGHT UP MY LIFE",
                      "MELROSE PLACE YOUR BETS",
                      "COFFEE SHOP TILL YOU DROP",
                      "POKER NIGHT OF THE LIVING DEAD",
                      "BLUSHING BRIDE OF FRANKENSTEIN",
                      "LOOK ON THE BRIGHT SIDE OF FRENCH FRIES",
                      "APPLE PIE A LA MODE OF TRANSPORTATION",
                      "RUNNING FOR OFFICE CUBICLE",
                      "VIOLIN STRING CHEESE",
                      "LOSING YOUR FIRST TOOTH FAIRY",
                      "FASHIONABLY LATE BLOOMER",
                      "PAMELA ANDERSON COOPER",
                      "VOLCANIC ROCK PAPER SCISSORS",
                      "TOO MUCH INFORMATION BOOTH",
                      "PONTOON BRIDGE TOURNAMENT",
                      "MATTRESS SPRING FLING",
                      "DEBT CEILING FAN",
                      "IF THESE WALLS COULD TALK TURKEY",
                      "WISHFUL THINKING CAP",
                      "MEN IN BLACK BEAN SOUP",
                      "MAGIC CARPET CLEANING",
                      "DO YOU SPEAK GERMAN CHOCOLATE CAKE",
                      "LOCKER ROOM WITH A VIEW",
                      "THROUGH THICK AND THIN PIZZA CRUST",
                      "WORTH ITS WEIGHT IN GOLD RECORDS",
                      "SIRLOIN TIP OF THE ICEBERG",
                      "THE CALL OF THE WILD-GOOSE CHASE",
                      "I SLEPT LIKE A BABY BOOMER",
                      "SHAVING CREAM OF THE CROP",
                      "COSMETIC CASE OF MISTAKEN IDENTITY",
                      "WORDS OF WISDOM TEETH",
                      "SUPER BOWL OF FRUIT",
                      "DOUBLE DATE WITH DESTINY",
                      "A MATCH MADE IN HEAVEN HELP US",
                      "BEACH HOUSE OF CARDS",
                      "PEKING DUCK DUCK GOOSE",
                      "PRICE TAG YOU'RE IT",
                      "MONKEY BUSINESS CONFERENCE",
                      "POPSICLE STICK SHIFT",
                      "WRINKLE CREAM OF WHEAT",
                      "UNIVERSITY MARCHING BAND-AID",
                      "NO RIGHT TURN ON RED APPLES",
                      "ENGLISH CHANNEL SURFING",
                      "BOWLING PINS AND NEEDLES",
                      "LIKE A MEMBER OF THE FAMILY FEUD",
                      "ONE-WAY STREET PERFORMER",
                      "SCOTLAND YARD SALE",
                      "LONG LIVE THE KING-SIZE BED",
                      "SWEET & SOUR CHICKEN LITTLE",
                      "TO HAVE AND TO HOLD A GRUDGE",
                      "CATCH A FALLING STAR TREK",
                      "MADISON SQUARE GARDEN VEGETABLES",
                      "MILD MEDIUM AND HOT SALSA DANCING",
                      "STOMACH CRUNCH THE NUMBERS",
                      "PURE AS THE DRIVEN SNOW WHITE",
                      "BOWLING TROPHY WIFE",
                      "THE SUNSET STRIP OF BACON",
                      "SUBWAY PLATFORM SHOES",
                      "WOULD YOU MIND OVER MATTER",
                      "SOME LIKE IT HOT PASTRAMI SANDWICH",
                      "HUMPTY DUMPTY HAD A GREAT FALL SEMESTER",
                      "THE MERCHANT OF VENICE BEACH",
                      "STUDY HALL OF FAME",
                      "SCIENCE PROJECT RUNWAY",
                      "NONSTOP FLIGHTS OF FANCY",
                      "CHICKEN STOCK MARKET",
                      "FOLLOW THE YELLOW BRICK ROAD HOG",
                      "SOCIAL BUTTERFLY COLLECTION",
                      "YOU ARE THE SUNSHINE OF MY LIFE SAVINGS",
                      "A PAT ON THE BACK TO THE FUTURE",
                      "STUNT DOUBLE COUPONS",
                      "THIRD TIME'S THE CHARM BRACELET",
                      "LITTLE BOY BLUE WHALE",
                      "KEEP YOUR DISTANCE RUNNER",
                      "MEN ARE FROM MARS WOMEN ARE FROM VENUS FLYTRAP",
                      "A HEART OF GOLD COINS",
                      "SCRATCHING POST OFFICE",
                      "GYM BAG OF POTATO CHIPS",
                      "CRACKS IN THE SIDEWALK SALE",
                      "PRESS YOUR LUCK OF THE IRISH",
                      "EMERY BOARD OF DIRECTORS",
                      "WEDDING RING AROUND THE COLLAR",
                      "BED BATH & BEYOND THUNDERDOME",
                      "A FEAST FIT FOR A KING KONG",
                      "SUPERSONIC SPEED BUMP",
                      "BEER BELLY DANCER",
                      "SHALLOW END OF THE POOL TABLE"],
    "FunAndGames":["FLOATING DOWN A LAZY RIVER",
                   "DIVING NEAR CORAL REEFS",
                   "SEARCHING THE SKY FOR CONSTELLATIONS",
                   "FISHING ON THE HIGH SEAS",
                   "DANCING TO THE BEAT",
                   "PLAYING HORSESHOES",
                   "SPECTATOR SPORT",
                   "CRUISING IN A CATAMARAN",
                   "TRICK-OR-TREATING",
                   "WHITE-WATER RAFTING",
                   "OUTRIGGER CANOE RACE",
                   "PLAYING CHARADES",
                   "COLLEGE FOOTBALL",
                   "RIDING A UNICYCLE",
                   "SHUFFLEBOARD",
                   "BUILDING SANDCASTLES ON THE BEACH",
                   "PAINTING A PICTURE",
                   "PAPER AIRPLANES",
                   "MAKING A GAME-WINNING TOUCHDOWN CATCH",
                   "TRUTH OR DARE",
                   "WATER AEROBICS",
                   "ZIP-LINING THROUGH THE JUNGLE",
                   "SOLVING RIDDLES",
                   "STRIKES AND SPARES",
                   "TEXTING A SMILEY FACE",
                   "RACING DOWN THE WATER SLIDE",
                   "WALKING THE FREEDOM TRAIL IN BOSTON",
                   "SWIMMING WITH DOLPHINS",
                   "ROAD TRIPPING",
                   "MINIATURE GOLF",
                   "ROLLER DERBY",
                   "MARCH MADNESS",
                   "PLAYING SIMON SAYS",
                   "TOUCH FOOTBALL",
                   "EXPLORING THE COASTLINE IN A KAYAK",
                   "WINDSURFING IN THE CARIBBEAN",
                   "PLAYING ALONG AT HOME",
                   "DONKEY KONG",
                   "SPACE INVADERS",
                   "SCORING THE WINNING GOAL",
                   "BACKGAMMON BOARD",
                   "SPLASHING IN THE CRYSTAL CLEAR OCEAN",
                   "RIDING THE WAVES",
                   "TIC-TAC-TOE",
                   "PRACTICING MY FLAMENCO DANCING",
                   "BACKSTROKE AND SIDESTROKE",
                   "BACKYARD SWING SET",
                   "LOOKING AT STARS THROUGH A TELESCOPE",
                   "KNOCK-KNOCK JOKE",
                   "MERRY-GO-ROUND",
                   "THROWING A BOOMERANG",
                   "RUNNING THE BASES"],
    "Person":["PREVIOUS OCCUPANT",
              "MOUNTAIN CLIMBER",
              "SECRET ADMIRER",
              "BELLE OF THE BALL",
              "AVID HOCKEY FAN",
              "CHESS PLAYER",
              "FIERCE COMPETITOR",
              "A REAL GO-GETTER",
              "NEW KID IN TOWN",
              "MYSTERIOUS MASTER MAGICIAN",
              "EGYPTIAN PHARAOH",
              "GOLFING BUDDY",
              "SUSPICIOUS CHARACTER",
              "JOLLY GOOD FELLOW",
              "SIDEKICK",
              "GOODY TWO-SHOES",
              "STRAIGHT-A STUDENT",
              "ROCK CLIMBER",
              "POSTER BOY",
              "COMRADE IN ARMS",
              "COMPANY BIGWIG",
              "LIGHTHOUSE KEEPER",
              "JOVIAL HOST",
              "DON JUAN",
              "MILD-MANNERED REPORTER",
              "DADDY'S LITTLE GIRL",
              "MAJORITY OWNER",
              "HOPELESS ROMANTIC",
              "SILENT PARTNER",
              "MURAL PAINTER",
              "BACKPACKER",
              "BACHELOR",
              "HALL OF FAMER",
              "POWER BROKER",
              "OLDER BROTHER",
              "MY SWEETHEART",
              "LAST MAN STANDING",
              "SUPREME COURT JUSTICE",
              "GRADUATE ASSISTANT",
              "THE WORLD'S FASTEST MAN",
              "TOP DRAFT PICK",
              "WEALTHY WOMAN",
              "CROSS-COUNTRY RUNNER",
              "BEAUTY PAGEANT JUDGE",
              "A SOPHOMORE",
              "MOTHER'S LITTLE HELPER",
              "TEAM CAPTAIN",
              "GRAND MARSHAL OF THE PARADE",
              "TIGHTROPE WALKER",
              "FIGURE SKATER",
              "CONTEMPORARY ARTIST",
              "THE STRONG SILENT TYPE",
              "A REAL CHARMER",
              "YOUR BIGGEST FAN"],
    "Event":["ROMANTIC GONDOLA RIDE",
             "AWESOME HELICOPTER TOUR",
             "THE FIRST DAY OF SCHOOL",
             "GUIDED SNORKELING TRIP",
             "WINNING A NARROW VICTORY",
             "CELEBRITY GOLF TOURNAMENT",
             "COSTUME PARTY",
             "PUMPKIN CARVING CONTEST",
             "CLIMBING TO THE TOP OF MOUNT EVEREST",
             "UNBELIEVABLE TRANSFORMATION",
             "REACHING THE TOP OF THE MOUNTAIN",
             "HOLIDAY PARTY",
             "DAZZLING FIREWORKS DISPLAY",
             "ANNUAL HULA FESTIVAL",
             "BUILDING A BONFIRE",
             "DAYBREAK",
             "ALPINE ADVENTURE",
             "CANDLELIGHT DINNER FOR TWO",
             "BREAKFAST IN BED",
             "BEING CARRIED OVER THE THRESHOLD",
             "A HUGE MILESTONE",
             "CHANCE ENCOUNTER",
             "MAJOR SCIENTIFIC BREAKTHROUGH",
             "CHAMPAGNE BRUNCH",
             "HOT STONE MASSAGE",
             "THE YEAR OF THE HORSE",
             "ANNUAL COMPANY PICNIC",
             "CLASS REUNION",
             "MAKEOVER AND MAKEUP CONSULTATION",
             "TAKING FLIGHT",
             "SLUMBER PARTY",
             "GIRLS' NIGHT OUT",
             "SEEING A MIRAGE",
             "CROSSING THE GOLDEN GATE BRIDGE",
             "BIRTHDAY BASH",
             "EMBARKING ON A VOYAGE",
             "PUBLIC APOLOGY",
             "AN EXTRAORDINARY EXPERIENCE",
             "GUIDED TOUR OF ANCIENT RUINS",
             "PRIVATE DINING UNDER THE STARS",
             "SETTING A WORLD RECORD",
             "REHEARSAL DINNER",
             "SPRING FASHION SHOW",
             "FAIRY-TALE WEDDING",
             "PRIVATE PARTY",
             "A NICE LONG WEEKEND",
             "PHOTO FINISH",
             "TOURNAMENT OF CHAMPIONS",
             "GRADUATING WITH HONORS",
             "JOYOUS OCCASION"],
    "Things":["MYTHS AND LEGENDS",
              "HOME MOVIES",
              "BONGO DRUMS",
              "TRADITIONS AND MANNERS",
              "WOODEN BUNK BEDS",
              "BEAUTY AND WELLNESS",
              "GLOSSARY AND INDEX",
              "GOOD TABLE MANNERS",
              "NICKELS DIMES AND QUARTERS",
              "FANCY DRESS SHOES",
              "STACKS OF CHIPS",
              "DIPLOMAS HANGING ON THE WALL",
              "UNSPOILED NATURAL WONDERS",
              "THE FINEST AMAZING AMENITIES",
              "PASSPORTS & VISAS",
              "HOLIDAY ORNAMENTS",
              "TENT POLES & STAKES",
              "QUIZ ANSWERS",
              "RETURNS AND REFUNDS",
              "PARADE FLOATS",
              "GOALS AND ASPIRATIONS",
              "HEADPHONES",
              "PROBING QUESTIONS",
              "BICEPS AND TRICEPS",
              "KITCHEN APPLIANCES",
              "HEARTWARMING STORIES",
              "NUTRITION & PHYSICAL FITNESS",
              "PANT CUFFS",
              "THOUSANDS OF DOLLARS",
              "LATITUDE & LONGITUDE",
              "WIND-CHILL FACTOR",
              "FREEZING TEMPERATURES",
              "WITTY PUNS",
              "JUNE JULY AND AUGUST",
              "PLUSH BATHROBES",
              "FAMILY VALUES",
              "BLACK TIE AND TAILS",
              "BEAUTIFUL FRESH FLOWER LEIS",
              "MINERAL SPRINGS",
              "VISUAL EFFECTS",
              "INVESTMENT TIPS",
              "JAW-DROPPING ICE FORMATIONS",
              "HISTORICAL CHARM AND ELEGANCE",
              "CHERISHED MEMORIES",
              "HITS AND MISSES",
              "MANICURES PEDICURES & FACIALS",
              "LEGENDARY WAVES OF THE NORTH SHORE",
              "JACUZZI BUBBLES",
              "HIGHWAYS FREEWAYS & INTERSTATES",
              "NOUNS AND PRONOUNS",
              "BRAINS AND BRAWN",
              "HOURS OF OPERATION",
              "DEPARTMENT STORE MANNEQUINS",
              "OVERDUE LIBRARY BOOKS",
              "SIX THOUSAND SHOWS!",
              "BIRTHDAY CANDLES",
              "GARDENS WATERFALLS AND BEACHES",
              "LONG EYELASHES",
              "PUSH-UPS AND SIT-UPS",
              "HUGS AND KISSES",
              "VIEWS OF THE BRILLIANT BLUE SEA",
              "PARTY DECORATIONS",
              "FACTS AND FIGURES",
              "JUMPER CABLES",
              "HAND-ROLLED CIGARS",
              "PLIERS HAMMERS AND SCREWDRIVERS"],
    "FoodAndDrink":["SIGNATURE COCKTAILS",
                    "CLASSIC ITALIAN LASAGNA",
                    "GRAHAM CRACKER PIE CRUST",
                    "A WHOLE HONEYDEW",
                    "PECAN PIE TOPPED WITH WHIPPED CREAM",
                    "AWARD-WINNING BARBECUE SAUCE",
                    "WHOLESOME HOME-COOKED MEAL",
                    "GRILLED CHEESE SANDWICH",
                    "THE MAIN COURSE",
                    "SPICY SALMON WITH CARAMELIZED ONIONS",
                    "BAKED HAM",
                    "CRISPY COCONUT CHICKEN",
                    "GUACAMOLE MADE TABLESIDE",
                    "GOURMET POPCORN",
                    "CHOCOLATE CANDY",
                    "TRADITIONAL JAMAICAN JERK CHICKEN",
                    "MANGO PINEAPPLE PAPAYA SALAD",
                    "HANDFUL OF TRAIL MIX",
                    "HUNGARIAN GOULASH",
                    "BLUE MOUNTAIN COFFEE BEANS",
                    "CHOWDER",
                    "CHOCOLATE-COVERED STRAWBERRIES",
                    "HOT FUDGE SUNDAE",
                    "CHOCOLATE MACADAMIA PANCAKES",
                    "TOMATOES CARROTS CELERY AND BEETS",
                    "GREEN SEEDLESS GRAPES",
                    "RIPE CANTALOUPE",
                    "NAVEL ORANGE",
                    "FRUITY TROPICAL COCKTAILS",
                    "SPICY CHILI PEPPERS",
                    "KLONDIKE BAR",
                    "SPICY GUACAMOLE",
                    "BREAD PUDDING",
                    "FRENCH VANILLA YOGURT",
                    "TWO GLASSES OF WINE",
                    "CREAMY VANILLA ICE CREAM CAKE",
                    "BOX OF CANDIES",
                    "NUTS AND CHOCOLATE",
                    "CAVIAR CAPERS AND CRACKERS",
                    "EXQUISITE DESIGNER CAKES",
                    "ALASKAN KING CRAB",
                    "BUTTERSCOTCH COOKIES",
                    "VEGETABLE JUICE",
                    "PINEAPPLE FRUIT BOWL",
                    "PEPPERMINT TEA",
                    "GERMAN POTATO SALAD",
                    "STUFFED PASTA SHELLS",
                    "CHEESE DANISH",
                    "SOURDOUGH BREAD",
                    "DOUBLE SHOT MOCHA LATTE",
                    "BISCUITS AND GRAVY",
                    "SNACKS FOR THE CAR",
                    "REFRESHING COCONUT WATER",
                    "CHOCOLATE CHIP SCONE",
                    "FRENCH PRESS COFFEE",
                    "QUICHE LORRAINE",
                    "A BOWL OF DELICIOUS GOULASH",
                    "CHOCOLATE SUNDAE WITH A CHERRY ON TOP",
                    "CRAB-STUFFED LOBSTER TAILS",
                    "ICE-COLD LEMONADE",
                    "A CUP OF HOT COCOA",
                    "CHINESE CHICKEN SALAD",
                    "BAMBOO SHOOTS",
                    "GRAPEFRUIT JUICE",
                    "CAKE ICING",
                    "KIWI BANANA AND PASION FRUIT"],
    "SongLyrics":["I LOVE THE NIGHTLIFE",
                  "TEACH YOUR CHILDREN WELL",
                  "HEAVEN IS A PLACE ON EARTH",
                  "SUMMERTIME SUMMERTIME SUM SUM SUMMERTIME",
                  "ALL MY BAGS ARE PACKED I'M READY TO GO",
                  "YOU WEAR IT WELL",
                  "VERY SUPERSTITIOUS",
                  "DO YOU COME FROM A LAND DOWN UNDER?",
                  "ROCKY MOUNTAIN HIGH",
                  "A HOLLY JOLLY CHRISTMAS",
                  "I'M IN LOVE I'M ALL SHOOK UP",
                  "LIKE A BOLT OUT OF THE BLUE",
                  "I NEVER KNEW LOVE LIKE THIS BEFORE",
                  "SUNSHINE ON MY SHOULDERS",
                  "YOU LOOK WONDERFUL TONIGHT",
                  "SHE LOVES YOU YEAH YEAH YEAH",
                  "I WANT TO KNOW WHAT LOVE IS",
                  "WE WILL WE WILL ROCK YOU",
                  "ONCE TWICE THREE TIMES A LADY",
                  "IT'S A BEAUTIFUL DAY",
                  "YOU GIVE ME FEVER WHEN YOU KISS ME",
                  "I WILL ALWAYS LOVE YOU",
                  "UNDER THE BOARDWALK DOWN BY THE SEA",
                  "THAT'S WHAT FRIENDS ARE FOR",
                  "HERE'S MY NUMBER SO CALL ME MAYBE",
                  "SCHOOL'S OUT FOR SUMMER",
                  "I WISH THEY ALL COULD BE CALIFORNIA GIRLS",
                  "MAMA I'M COMING HOME",
                  "SURF CITY HERE WE COME",
                  "O BEAUTIFUL FOR SPACIOUS SKIES",
                  "WALK LIKE A MAN TALK LIKE A MAN"],
    "SameLetter":["CALCULUS CHEMISTRY CIVICS",
                  "SLURPING STRAWBERRY SMOOTHIES",
                  "SOOTHING SPA SERVICES",
                  "CRISP CHILLED CUCUMBERS",
                  "BLUE BIKINI BOTTOMS",
                  "SCARY SUSPENSEFUL STORY",
                  "GOBLINS GREMLINS & GARGOYLES",
                  "CUPCAKES COBBLERS & COOKIES",
                  "FABULOUS FLAVORFUL FOOD",
                  "MONSTER MOVIE MARATHON",
                  "PURE PERFECT PARADISE",
                  "CLIMATE CULTURE CUSTOMS",
                  "FLIPPING FLUFFY FLAPJACKS",
                  "LOVELY LUSH LANDSCAPES",
                  "SUPERHUMAN STRENGTH & SPEED",
                  "FOOD FUN & FESTIVITIES",
                  "SOOTHING SERENE SETTING",
                  "BUSBOYS BARTENDERS & BOUNCERS",
                  "CLEVER CROSSWORD CLUES",
                  "PEACHES PLUMS & PRICKLY PEARS",
                  "FANTASTIC FUN-FILLED FRIDAYS",
                  "CLASHING CLANGING CYMBALS",
                  "DETAILED DRIVING DIRECTIONS",
                  "BLUE BABY BOOTIES",
                  "CREAM CHEESE COFFEE CAKE",
                  "PERSONALIZED PLUSH PILLOWS",
                  "MOM'S MONOGRAMMED MUG",
                  "CUTE CUDDLY CALICO CATS",
                  "LUCK LITERATURE & LEPRECHAUNS",
                  "BEACHES BASEBALL & BARBECUES",
                  "WONDERFUL WARM WEATHER",
                  "GIZMOS GADGETS & GAMES",
                  "WATERPROOF WRISTWATCH",
                  "TEACHING TODDLERS TO TALK"],
    "ShowBiz":["OUTSTANDING DRAMA SERIES",
               "A TELEVISION EVENT",
               "INTERNET RADIO",
               "BRAD PITT STARS IN WORLD WAR Z",
               "LEONARDO DICAPRIO STARS IN THE GREAT GATSBY",
               "NEW ORLEANS JAZZ",
               "SUNDAY MATINEE",
               "FAVORITE THEME SONG",
               "MUSIC SENSATION KATY PERRY",
               "THE HOTTEST SHOW IN TOWN",
               "AN ALL-STAR CAST",
               "REUNION CONCERT TOUR",
               "MTV VIDEO MUSIC AWARDS",
               "SPECIAL APPEARANCE",
               "INDEPENDENT FILM",
               "UPCOMING MOVIE TRAILERS",
               "SANDRA BULLOCK STARS IN GRAVITY",
               "TELEVISION & FILM STAR",
               "WORLDWIDE BOX OFFICE SMASH",
               "MOVIE STUNTMAN",
               "SILLY SONG LYRICS",
               "RHYTHM GUITAR",
               "AUDITIONING FOR THE LEAD ROLE",
               "MOVIE SOUNDTRACK",
               "CAMEO APPEARANCE",
               "SCREENWRITERS & SCREENPLAYS",
               "TERRIFIC STEEL DRUM MUSIC",
               "POP MUSIC STAR BRUNO MARS",
               "TEN-PIECE BRASS BAND",
               "JOHN TRAVOLTA IN HAIRSPRAY",
               "SINGING SUPERSTAR CELINE DION",
               "ORIGINAL BROADWAY CAST",
               "HOLLYWOOD LEGEND SEAN CONNERY"],
    "OnTheMap":["LEXINGTON KENTUCKY",
                "JACKSON MISSISSIPPI",
                "MONTGOMERY ALABAMA",
                "BORA BORA",
                "RED ROCK CANYON",
                "AUSTRALIA & NEW ZEALAND",
                "MONTREAL CANADA",
                "BEIJING CHINA",
                "DENMARK & NORWAY",
                "PANAMA CITY PANAMA",
                "YOUNGSTOWN OHIO",
                "SOUTH DAKOTA",
                "UNITED STATES VIRGIN ISLANDS",
                "LINCOLN NEBRASKA",
                "THE NORTHERN HEMISPHERE",
                "WESTERN EUROPE",
                "THE YUKON TERRITORY",
                "AUSTIN TEXAS",
                "THE GRAND CANAL IN VENICE",
                "CANARY ISLANDS",
                "BALTIMORE MARYLAND",
                "NORTH CAROLINA",
                "THE UNITED KINGDOM",
                "THE CZECH REPUBLIC",
                "DISTRICT OF COLUMBIA",
                "LOS ANGELES CALIFORNIA",
                "PHOENIX ARIZONA",
                "HOLLYWOOD AND VINE",
                "THE BAHAMAS",
                "MONTEGO BAY",
                "THE CARIBBEAN SEA",
                "BARBADOS",
                "LOUISIANA",
                "NEW HAMPSHIRE",
                "HONOLULU",
                "JACKSON HOLE WYOMING",
                "BOSTON MASSACHUSETTS",
                "NEWPORT RHODE ISLAND",
                "SANTA FE NEW MEXICO"],
    "People":["THE OPPOSING TEAM",
              "AUTHENTIC MARIACHI BAND",
              "DALLAS COWBOYS CHEERLEADERS",
              "GREAT AUNTS AND UNCLES",
              "SHIP'S CAPTAIN AND FIRST MATE",
              "CIRCUS PERFORMERS",
              "CHOOSY KIDS",
              "AIRLINE PASSENGERS",
              "FUTURE GENERATIONS",
              "ALL-STAR TEAM",
              "EXECUTIVES AND MANAGERS",
              "GIVERS AND TAKERS",
              "EARLY BIRDS",
              "A CAPPELLA GROUP",
              "BEST FRIENDS FOREVER",
              "BOYFRIEND & GIRLFRIEND",
              "WORLD FAMOUS CHEFS",
              "THE ROYAL FAMILY",
              "MOVERS AND SHAKERS",
              "DOUBLES PARTNERS",
              "FAITHFUL FANS",
              "THE WHOLE FAMILY",
              "ENTHUSIASTIC SUPPORTERS",
              "COLLEGE ROOMMATES",
              "FACEBOOK FRIENDS",
              "DANCE PARTNERS",
              "OVERACHIEVERS",
              "LIKE-MINDED INDIVIDUALS",
              "HUMAN PYRAMID",
              "QUALIFIED APPLICANTS",
              "HAPPY HOMEOWNERS",
              "PICNICKERS",
              "FORMER TEAMMATES",
              "BASEBALL PLAYERS"],
    "AroundTheHouse":["FLUFFY PILLOWS",
                      "FULL-LENGTH WALL MIRROR",
                      "SCENTED CANDLES",
                      "COLOR-SAFE BLEACH",
                      "WELCOME MAT",
                      "GROCERY LIST",
                      "DISPLAY EXHIBIT",
                      "GARDEN HOSE",
                      "DECORATVE PILLOWS",
                      "SEWING KIT",
                      "SELF-HELP BOOKS",
                      "MONKEY WRENCH",
                      "WATER FILTER",
                      "PERFUME AND COLOGNE",
                      "BATH TOWELS",
                      "LAVA LAMP",
                      "CONSTRUCTION PAPER",
                      "CRYSTAL CHANDELIER",
                      "GRANDFATHER CLOCK",
                      "ELECTRIC TOOTHBRUSH",
                      "VIDEO GAMES",
                      "SECTIONAL SOFA",
                      "CERAMIC DALMATIAN",
                      "DESIGNER THROW PILLOWS",
                      "BLACK-AND-WHITE PHOTOGRAPHS",
                      "ENGRAVED JEWELRY BOX",
                      "PILLOWS AND COMFORTERS",
                      "ELECTRIC LAWN MOWER",
                      "GARDENING GLOVES",
                      "HEAVY-DUTY TOOL CABINET",
                      "WINDOW SHADES",
                      "LAWN FURNITURE",
                      "A PAIR OF BINOCULARS"],
    "LivingThings":["ROARING MOUNTAIN LIONS",
                    "CHERRY BLOSSOMS",
                    "A LITTER OF SIAMESE KITTENS",
                    "WILD STALLIONS",
                    "GIGANTIC INSECTS",
                    "DOLPHINS DOING FLIPS",
                    "FORGET-ME-NOTS",
                    "A FLOCK OF SEAGULLS",
                    "GARDEN FLOWERS",
                    "RED CARNATIONS",
                    "PELICANS & PEACOCKS",
                    "FLOCK OF COLORFUL TOUCANS",
                    "MONARCH BUTTERFLIES",
                    "BOUQUET OF ROSES",
                    "ARABIAN HORSES",
                    "A SCHOOL OF FISH",
                    "FRAGRANT WILDFLOWERS",
                    "YELLOW ROSES",
                    "POTTED PLANTS",
                    "YELLOW JACKETS",
                    "GRACEFUL SEA TURTLES",
                    "MONKEYS LEOPARDS AND PARROTS"],
    "SameName":["SEWING AND SLOT MACHINE",
                "POKER & POTATO CHIPS",
                "BABY & METEOR SHOWER",
                "MARCHING AND RUBBER BAND",
                "RELIEF AND WATER PITCHER",
                "ANNIVERSARY & CREDIT CARD",
                "SLEEPING & TEA BAG",
                "BINGO AND BIRTHDAY CARD",
                "LOVE AND INTERNET CONNECTION",
                "INFERIORITY & APARTMENT COMPLEX",
                "ELEPHANT AND SWIMMING TRUNKS",
                "FLORIDA AND CAR KEYS",
                "DORM AND ELBOW ROOM",
                "COMMENCEMENT AND CAR SPEAKERS",
                "BIRTH AND GIFT CERTIFICATE",
                "COFFEE AND LUCKY BREAK"],
    "TheEighties":["WALK LIKE AN EGYPTIAN",
                   "MYSTIC PIZZA",
                   "KNIGHT RIDER",
                   "THE EYE OF THE TIGER",
                   "WAKE ME UP BEFORE YOU GO-GO",
                   "RAPTURE BY BLONDIE",
                   "THE BREAKFAST CLUB",
                   "TELEVISION MINISERIES LONESOME DOVE",
                   "SIXTEEN CANDLES",
                   "REVENGE OF THE NERDS",
                   "PRETTY IN PINK",
                   "HUNGRY LIKE THE WOLF BY DURAN DURAN",
                   "SOLVING A RUBIK'S CUBE",
                   "BRUCE SPRINGSTEEN'S BORN IN THE U.S.A.",
                   "NATIONAL LAMPOON'S VACATION",
                   "THREE MEN AND A BABY"],
    "TheNinties":["DON JOHNSON STARS IN NASH BRIDGES",
                  "KEVIN COSTNER IN DANCES WITH WOLVES",
                  "THELMA & LOUISE",
                  "HARRISON FORD IN AIR FORCE ONE",
                  "ALICIA SILVERSTONE STARS IN CLUELESS",
                  "SAVED BY THE BELL",
                  "HOME ALONE",
                  "THE NANNY",
                  "DAWSON'S CREEK",
                  "AMERICAN GLADIATORS",
                  "DOOGIE HOWSER M.D.",
                  "ACHY BREAKY HEART",
                  "WILL SMITH IN INDEPENDENCE DAY",
                  "ROBIN WILLIAMS AS MRS. DOUBTFIRE"],
    "Quotation":["I THINK I CAN I THINK I CAN",
                 "HERE'S JOHNNY",
                 "NOW DASHER! NOW DANCER! NOW PRANCER AND VIXEN!",
                 "PARTING IS SUCH SWEET SORROW",
                 "ROME WASN'T BUILT IN A DAY",
                 "DRIVERS START YOUR ENGINES",
                 "ROW ROW ROW YOUR BOAT",
                 "DO YOU KNOW THE MUFFIN MAN?",
                 "IT'S ALL GREEK TO ME",
                 "AND TO THE REPUBLIC FOR WHICH IT STANDS",
                 "O CAPTAIN! MY CAPTAIN!"],
    "ProperName":["ALBERT EINSTEIN",
                  "ERNEST HEMINGWAY",
                  "DOLLY PARTON",
                  "FRANK SINATRA",
                  "ALFRED HITCHCOCK",
                  "BUFFALO BILLS",
                  "PRESIDENT THEODORE ROOSEVELT",
                  "JENNIFER LAWRENCE",
                  "ROBERT REDFORD",
                  "CYNDI LAUPER",
                  "SARAH JESSICA PARKER",
                  "REESE WITHERSPOON",
                  "F. SCOTT FITZGERALD",
                  "EDGAR ALLAN POE",
                  "SUSAN B. ANTHONY",
                  "SUSAN SARANDON",
                  "DONALD TRUMP",
                  "CANDACE OWENS",
                  "DAVE RAMSEY"],
    "Occupation":["COMMERCIAL ARCHITECT",
                  "GYMNASTICS COACH",
                  "PERSONAL ASSISTANT",
                  "CHEMICAL ENGINEER",
                  "HIGH SCHOOL CHEMISTRY TEACHER",
                  "TRAIN CONDUCTOR",
                  "SCIENCE FICTION WRITER",
                  "BANQUET WAITER",
                  "EQUIPMENT MANAGER",
                  "PROFESSIONAL BUTLER",
                  "MARKETING SPECIALIST",
                  "CAREER COUNSELOR",
                  "OPTICIAN",
                  "TELEVISION CRITIC",
                  "SPORTSWRITER",
                  "LIFEGUARD",
                  "AUDITOR",
                  "ARTIST",
                  "PROGRAMMER"],
    "FictionalCharacter":["GRUMPY",
                          "GOOFY",
                          "MICKEY MOUSE",
                          "DONALD DUCK",
                          "SHELDON COOPER",
                          "ASLAN",
                          "ARTHUR",
                          "WONDER WOMAN",
                          "FREDDY KRUEGER",
                          "SHAPE-SHIFTER",
                          "MARVEL SUPERHERO THOR",
                          "FIRE-BREATHING DRAGON",
                          "LUKE SKYWALKER",
                          "CURIOUS GEORGE",
                          "CAPTAIN KIRK",
                          "MALIBU BARBIE",
                          "MYTHOLOGICAL HERO ACHILLES",
                          "PETER COTTONTAIL",
                          "HUCKLEBERRY FINN",
                          "SHERLOCK HOLMES",
                          "MOTHER GOOSE",
                          "BART SIMPSON",
                          "DARTH VADER"],
    "CollegeLife":["PROFESSOR'S OFFICE HOURS",
                   "GRADE POINT AVERAGE",
                   "UNIVERSITY BOOKSTORE",
                   "COURSE CATALOG"],
    "InTheKitchen":["PROGRAMMABLE COFFEEMAKER",
                    "TWELVE-SPEED BLENDER",
                    "WOOD-BURNING STOVE",
                    "CORKSCREW",
                    "COUNTERTOP MICROWAVE",
                    "ELECTRIC CAN OPENER",
                    "CHEESE GRATER",
                    "POTATO PEELER",
                    "STAINLESS STEEL COLANDER",
                    "MARBLE COUNTERTOP",
                    "SLOW COOKER AND STEAMER",
                    "MEASURING CUPS"],
    "LivingThing":["CHAMPION RACEHORSE",
                   "MEADOWLARK",
                   "A BLACK CAT CROSSING YOUR PATH",
                   "TOY FOX TERRIER",
                   "EUCALYPTUS TREE",
                   "ALASKA SALMON",
                   "SIBERIAN TIGER",
                   "HONEYSUCKLE",
                   "PAINTED TURTLE",
                   "NEWBORN PUPPY",
                   "BABY'S BREATH",
                   "SYCAMORE TREE",
                   "LUSH JUNGLE VEGETATION",
                   "JELLYFISH",
                   "DADDY LONGLEGS"]
}
